// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sender.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Destiny int32

const (
	Destiny_QUEUE    Destiny = 0
	Destiny_EXCHANGE Destiny = 1
)

var Destiny_name = map[int32]string{
	0: "QUEUE",
	1: "EXCHANGE",
}

var Destiny_value = map[string]int32{
	"QUEUE":    0,
	"EXCHANGE": 1,
}

func (x Destiny) String() string {
	return proto.EnumName(Destiny_name, int32(x))
}

func (Destiny) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dec65ed00f2bd807, []int{0}
}

type SenderArgs struct {
	Header               map[string]string `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DestinyType          Destiny           `protobuf:"varint,2,opt,name=destiny_type,json=destinyType,proto3,enum=sender.Destiny" json:"destiny_type,omitempty"`
	Destination          string            `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Content              []byte            `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SenderArgs) Reset()         { *m = SenderArgs{} }
func (m *SenderArgs) String() string { return proto.CompactTextString(m) }
func (*SenderArgs) ProtoMessage()    {}
func (*SenderArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_dec65ed00f2bd807, []int{0}
}

func (m *SenderArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderArgs.Unmarshal(m, b)
}
func (m *SenderArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderArgs.Marshal(b, m, deterministic)
}
func (m *SenderArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderArgs.Merge(m, src)
}
func (m *SenderArgs) XXX_Size() int {
	return xxx_messageInfo_SenderArgs.Size(m)
}
func (m *SenderArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SenderArgs proto.InternalMessageInfo

func (m *SenderArgs) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SenderArgs) GetDestinyType() Destiny {
	if m != nil {
		return m.DestinyType
	}
	return Destiny_QUEUE
}

func (m *SenderArgs) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *SenderArgs) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Bool struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_dec65ed00f2bd807, []int{1}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterEnum("sender.Destiny", Destiny_name, Destiny_value)
	proto.RegisterType((*SenderArgs)(nil), "sender.SenderArgs")
	proto.RegisterMapType((map[string]string)(nil), "sender.SenderArgs.HeaderEntry")
	proto.RegisterType((*Bool)(nil), "sender.Bool")
}

func init() {
	proto.RegisterFile("sender.proto", fileDescriptor_dec65ed00f2bd807)
}

var fileDescriptor_dec65ed00f2bd807 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0x4d, 0x9b, 0x34, 0x37, 0xe1, 0xfb, 0xc2, 0x45, 0x24, 0x74, 0x51, 0x42, 0x56,
	0xc1, 0x45, 0x84, 0x08, 0x62, 0xdd, 0x55, 0x0d, 0x76, 0x25, 0x3a, 0x5a, 0x70, 0x27, 0xa9, 0x1d,
	0x6c, 0x30, 0xcc, 0x94, 0xcc, 0x44, 0xc8, 0x53, 0xfb, 0x0a, 0xe6, 0xcf, 0x04, 0x0b, 0xee, 0xee,
	0xef, 0xde, 0x73, 0x66, 0x0e, 0x07, 0x5c, 0xc9, 0xf8, 0x8e, 0x95, 0xf1, 0xa1, 0x14, 0x4a, 0xa0,
	0xd9, 0x53, 0xf8, 0x4d, 0x00, 0x9e, 0xbb, 0x71, 0x55, 0x7e, 0x48, 0xbc, 0x04, 0x73, 0xcf, 0xb2,
	0x86, 0x7c, 0x12, 0x18, 0x91, 0x93, 0x2c, 0x62, 0xed, 0xfa, 0xd5, 0xc4, 0xeb, 0x4e, 0x90, 0x72,
	0x55, 0xd6, 0x54, 0xab, 0x31, 0x01, 0x77, 0xc7, 0xa4, 0xca, 0x79, 0xfd, 0xa6, 0xea, 0x03, 0xf3,
	0xc7, 0x01, 0x89, 0xfe, 0x25, 0xff, 0x07, 0xf7, 0x5d, 0x7f, 0xa3, 0x8e, 0x16, 0xbd, 0x34, 0x1a,
	0x0c, 0x40, 0x63, 0xa6, 0x72, 0xc1, 0x7d, 0xa3, 0xb1, 0xd8, 0xf4, 0x78, 0x85, 0x3e, 0x58, 0xef,
	0x82, 0x2b, 0xc6, 0x95, 0x3f, 0x69, 0xae, 0x2e, 0x1d, 0x70, 0xbe, 0x04, 0xe7, 0x28, 0x06, 0x7a,
	0x60, 0x7c, 0xb2, 0xba, 0xc9, 0xdc, 0x3e, 0xd1, 0x8e, 0x78, 0x02, 0xd3, 0xaf, 0xac, 0xa8, 0xfa,
	0x24, 0x36, 0xed, 0xe1, 0x7a, 0x7c, 0x45, 0xc2, 0x05, 0x4c, 0x6e, 0x84, 0x28, 0xf0, 0x14, 0x4c,
	0xa9, 0x32, 0x55, 0xc9, 0xce, 0x36, 0xa3, 0x9a, 0xce, 0x42, 0xb0, 0x74, 0x5c, 0xb4, 0x61, 0xfa,
	0xb4, 0x49, 0x37, 0xa9, 0x37, 0x42, 0x17, 0x66, 0xe9, 0xeb, 0xed, 0x7a, 0xf5, 0x70, 0x9f, 0x7a,
	0x24, 0x59, 0x82, 0xd9, 0x17, 0x82, 0xe7, 0x60, 0x3d, 0x56, 0xdb, 0x22, 0x97, 0x7b, 0xc4, 0xbf,
	0x5d, 0xcd, 0xdd, 0x61, 0xd7, 0x7e, 0x19, 0x8e, 0x22, 0xb2, 0x35, 0xbb, 0xfe, 0x2f, 0x7e, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0xd0, 0x86, 0x6c, 0x8f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SenderClient is the client API for Sender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SenderClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (Sender_PublishClient, error)
}

type senderClient struct {
	cc grpc.ClientConnInterface
}

func NewSenderClient(cc grpc.ClientConnInterface) SenderClient {
	return &senderClient{cc}
}

func (c *senderClient) Publish(ctx context.Context, opts ...grpc.CallOption) (Sender_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sender_serviceDesc.Streams[0], "/sender.Sender/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &senderPublishClient{stream}
	return x, nil
}

type Sender_PublishClient interface {
	Send(*SenderArgs) error
	CloseAndRecv() (*Bool, error)
	grpc.ClientStream
}

type senderPublishClient struct {
	grpc.ClientStream
}

func (x *senderPublishClient) Send(m *SenderArgs) error {
	return x.ClientStream.SendMsg(m)
}

func (x *senderPublishClient) CloseAndRecv() (*Bool, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Bool)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SenderServer is the server API for Sender service.
type SenderServer interface {
	Publish(Sender_PublishServer) error
}

// UnimplementedSenderServer can be embedded to have forward compatible implementations.
type UnimplementedSenderServer struct {
}

func (*UnimplementedSenderServer) Publish(srv Sender_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterSenderServer(s *grpc.Server, srv SenderServer) {
	s.RegisterService(&_Sender_serviceDesc, srv)
}

func _Sender_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SenderServer).Publish(&senderPublishServer{stream})
}

type Sender_PublishServer interface {
	SendAndClose(*Bool) error
	Recv() (*SenderArgs, error)
	grpc.ServerStream
}

type senderPublishServer struct {
	grpc.ServerStream
}

func (x *senderPublishServer) SendAndClose(m *Bool) error {
	return x.ServerStream.SendMsg(m)
}

func (x *senderPublishServer) Recv() (*SenderArgs, error) {
	m := new(SenderArgs)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sender.Sender",
	HandlerType: (*SenderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _Sender_Publish_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sender.proto",
}
