# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sender/sender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sender/sender.proto',
  package='sender',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13sender/sender.proto\x12\x06sender\"\xb8\x01\n\nSenderArgs\x12.\n\x06header\x18\x01 \x03(\x0b\x32\x1e.sender.SenderArgs.HeaderEntry\x12%\n\x0c\x64\x65stiny_type\x18\x02 \x01(\x0e\x32\x0f.sender.Destiny\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x1a-\n\x0bHeaderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x16\n\x04\x42ool\x12\x0e\n\x06status\x18\x01 \x01(\x08*\"\n\x07\x44\x65stiny\x12\t\n\x05QUEUE\x10\x00\x12\x0c\n\x08\x45XCHANGE\x10\x01\x32\x39\n\x06Sender\x12/\n\x07Publish\x12\x12.sender.SenderArgs\x1a\x0c.sender.Bool\"\x00(\x01\x62\x06proto3'
)

_DESTINY = _descriptor.EnumDescriptor(
  name='Destiny',
  full_name='sender.Destiny',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUEUE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXCHANGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=276,
)
_sym_db.RegisterEnumDescriptor(_DESTINY)

Destiny = enum_type_wrapper.EnumTypeWrapper(_DESTINY)
QUEUE = 0
EXCHANGE = 1



_SENDERARGS_HEADERENTRY = _descriptor.Descriptor(
  name='HeaderEntry',
  full_name='sender.SenderArgs.HeaderEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sender.SenderArgs.HeaderEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='sender.SenderArgs.HeaderEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=216,
)

_SENDERARGS = _descriptor.Descriptor(
  name='SenderArgs',
  full_name='sender.SenderArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sender.SenderArgs.header', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destiny_type', full_name='sender.SenderArgs.destiny_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination', full_name='sender.SenderArgs.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='sender.SenderArgs.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SENDERARGS_HEADERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=216,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='sender.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='sender.Bool.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=240,
)

_SENDERARGS_HEADERENTRY.containing_type = _SENDERARGS
_SENDERARGS.fields_by_name['header'].message_type = _SENDERARGS_HEADERENTRY
_SENDERARGS.fields_by_name['destiny_type'].enum_type = _DESTINY
DESCRIPTOR.message_types_by_name['SenderArgs'] = _SENDERARGS
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.enum_types_by_name['Destiny'] = _DESTINY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SenderArgs = _reflection.GeneratedProtocolMessageType('SenderArgs', (_message.Message,), {

  'HeaderEntry' : _reflection.GeneratedProtocolMessageType('HeaderEntry', (_message.Message,), {
    'DESCRIPTOR' : _SENDERARGS_HEADERENTRY,
    '__module__' : 'sender.sender_pb2'
    # @@protoc_insertion_point(class_scope:sender.SenderArgs.HeaderEntry)
    })
  ,
  'DESCRIPTOR' : _SENDERARGS,
  '__module__' : 'sender.sender_pb2'
  # @@protoc_insertion_point(class_scope:sender.SenderArgs)
  })
_sym_db.RegisterMessage(SenderArgs)
_sym_db.RegisterMessage(SenderArgs.HeaderEntry)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'sender.sender_pb2'
  # @@protoc_insertion_point(class_scope:sender.Bool)
  })
_sym_db.RegisterMessage(Bool)


_SENDERARGS_HEADERENTRY._options = None

_SENDER = _descriptor.ServiceDescriptor(
  name='Sender',
  full_name='sender.Sender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=278,
  serialized_end=335,
  methods=[
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='sender.Sender.Publish',
    index=0,
    containing_service=None,
    input_type=_SENDERARGS,
    output_type=_BOOL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDER)

DESCRIPTOR.services_by_name['Sender'] = _SENDER

# @@protoc_insertion_point(module_scope)
