// Code generated by protoc-gen-go. DO NOT EDIT.
// source: receiver.proto

package receiver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReceiverResponse struct {
	Filters              map[string]string `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Destination          string            `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Content              []byte            `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsARedelivery        bool              `protobuf:"varint,4,opt,name=is_a_redelivery,json=isARedelivery,proto3" json:"is_a_redelivery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReceiverResponse) Reset()         { *m = ReceiverResponse{} }
func (m *ReceiverResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiverResponse) ProtoMessage()    {}
func (*ReceiverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7296e1d2b388c5, []int{0}
}

func (m *ReceiverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverResponse.Unmarshal(m, b)
}
func (m *ReceiverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverResponse.Marshal(b, m, deterministic)
}
func (m *ReceiverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverResponse.Merge(m, src)
}
func (m *ReceiverResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiverResponse.Size(m)
}
func (m *ReceiverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverResponse proto.InternalMessageInfo

func (m *ReceiverResponse) GetFilters() map[string]string {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ReceiverResponse) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ReceiverResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ReceiverResponse) GetIsARedelivery() bool {
	if m != nil {
		return m.IsARedelivery
	}
	return false
}

type ReceiverArgs struct {
	QueueName            string   `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiverArgs) Reset()         { *m = ReceiverArgs{} }
func (m *ReceiverArgs) String() string { return proto.CompactTextString(m) }
func (*ReceiverArgs) ProtoMessage()    {}
func (*ReceiverArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b7296e1d2b388c5, []int{1}
}

func (m *ReceiverArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverArgs.Unmarshal(m, b)
}
func (m *ReceiverArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverArgs.Marshal(b, m, deterministic)
}
func (m *ReceiverArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverArgs.Merge(m, src)
}
func (m *ReceiverArgs) XXX_Size() int {
	return xxx_messageInfo_ReceiverArgs.Size(m)
}
func (m *ReceiverArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverArgs proto.InternalMessageInfo

func (m *ReceiverArgs) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

func init() {
	proto.RegisterType((*ReceiverResponse)(nil), "receiver.ReceiverResponse")
	proto.RegisterMapType((map[string]string)(nil), "receiver.ReceiverResponse.FiltersEntry")
	proto.RegisterType((*ReceiverArgs)(nil), "receiver.ReceiverArgs")
}

func init() {
	proto.RegisterFile("receiver.proto", fileDescriptor_4b7296e1d2b388c5)
}

var fileDescriptor_4b7296e1d2b388c5 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x24, 0x0d, 0xd0, 0xf4, 0x35, 0x40, 0xf5, 0x84, 0x90, 0x15, 0x09, 0x29, 0xca, 0x00, 0x5d,
	0x88, 0x50, 0x59, 0x50, 0xb7, 0x0c, 0xb0, 0xc1, 0xe0, 0x1f, 0x88, 0x42, 0xfb, 0x40, 0x16, 0xc1,
	0x2e, 0xb6, 0x53, 0x29, 0x1f, 0xce, 0x4e, 0xdc, 0xc6, 0x55, 0x05, 0xea, 0xf6, 0xee, 0x7c, 0xbe,
	0xb3, 0xef, 0xc1, 0xb9, 0xa6, 0x05, 0x89, 0x35, 0xe9, 0x7c, 0xa5, 0x95, 0x55, 0x18, 0x79, 0x9c,
	0xfd, 0x04, 0x30, 0xe1, 0x3d, 0xe0, 0x64, 0x56, 0x4a, 0x1a, 0xc2, 0x02, 0x86, 0xef, 0xa2, 0xb6,
	0xa4, 0x0d, 0x0b, 0xd2, 0x70, 0x3a, 0x9e, 0xdd, 0xe6, 0x3b, 0x83, 0xbf, 0xe2, 0xfc, 0x79, 0xab,
	0x7c, 0x92, 0x56, 0xb7, 0xdc, 0xdf, 0xc3, 0x14, 0xc6, 0x4b, 0x32, 0x56, 0xc8, 0xca, 0x0a, 0x25,
	0xd9, 0x20, 0x0d, 0xa6, 0x23, 0xbe, 0x4f, 0x21, 0x83, 0xe1, 0x42, 0x49, 0x4b, 0xd2, 0xb2, 0xb0,
	0x3b, 0x8d, 0xb9, 0x87, 0x78, 0x03, 0x17, 0xc2, 0x94, 0x55, 0xa9, 0x69, 0x49, 0xb5, 0xcb, 0x6a,
	0xd9, 0x71, 0xa7, 0x88, 0xf8, 0x99, 0x30, 0x05, 0xdf, 0x91, 0xc9, 0x1c, 0xe2, 0xfd, 0x70, 0x9c,
	0x40, 0xf8, 0x49, 0x6d, 0xf7, 0x64, 0x97, 0xe5, 0x46, 0xbc, 0x84, 0x93, 0x75, 0x55, 0x37, 0xd4,
	0xe7, 0x6f, 0xc1, 0x7c, 0xf0, 0x18, 0x64, 0x77, 0x10, 0xfb, 0x9f, 0x14, 0xfa, 0xc3, 0xe0, 0x35,
	0xc0, 0x77, 0x43, 0x0d, 0x95, 0xb2, 0xfa, 0xa2, 0xde, 0x62, 0xb4, 0x61, 0x5e, 0x3b, 0x62, 0xf6,
	0x02, 0x91, 0x97, 0xbb, 0x76, 0xfa, 0x19, 0xaf, 0xfe, 0xf7, 0xe2, 0xdc, 0x92, 0xe4, 0x70, 0x5f,
	0xd9, 0xd1, 0x7d, 0xf0, 0x76, 0xba, 0x59, 0xc3, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d,
	0xe6, 0xf8, 0xa0, 0x98, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReceiverClient is the client API for Receiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReceiverClient interface {
	Receive(ctx context.Context, in *ReceiverArgs, opts ...grpc.CallOption) (Receiver_ReceiveClient, error)
}

type receiverClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiverClient(cc grpc.ClientConnInterface) ReceiverClient {
	return &receiverClient{cc}
}

func (c *receiverClient) Receive(ctx context.Context, in *ReceiverArgs, opts ...grpc.CallOption) (Receiver_ReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Receiver_serviceDesc.Streams[0], "/receiver.Receiver/Receive", opts...)
	if err != nil {
		return nil, err
	}
	x := &receiverReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Receiver_ReceiveClient interface {
	Recv() (*ReceiverResponse, error)
	grpc.ClientStream
}

type receiverReceiveClient struct {
	grpc.ClientStream
}

func (x *receiverReceiveClient) Recv() (*ReceiverResponse, error) {
	m := new(ReceiverResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReceiverServer is the server API for Receiver service.
type ReceiverServer interface {
	Receive(*ReceiverArgs, Receiver_ReceiveServer) error
}

// UnimplementedReceiverServer can be embedded to have forward compatible implementations.
type UnimplementedReceiverServer struct {
}

func (*UnimplementedReceiverServer) Receive(req *ReceiverArgs, srv Receiver_ReceiveServer) error {
	return status.Errorf(codes.Unimplemented, "method Receive not implemented")
}

func RegisterReceiverServer(s *grpc.Server, srv ReceiverServer) {
	s.RegisterService(&_Receiver_serviceDesc, srv)
}

func _Receiver_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiverArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReceiverServer).Receive(m, &receiverReceiveServer{stream})
}

type Receiver_ReceiveServer interface {
	Send(*ReceiverResponse) error
	grpc.ServerStream
}

type receiverReceiveServer struct {
	grpc.ServerStream
}

func (x *receiverReceiveServer) Send(m *ReceiverResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Receiver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "receiver.Receiver",
	HandlerType: (*ReceiverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _Receiver_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "receiver.proto",
}
